### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by mll-enh** [forfourfnf/fnf-base#1]
yo. if you're gonna steal my code at least I should let you know 0.5.0 doesn't work
anyway kthx

**Comment by mll-enh** [comment]
also I don't really care abt the code thing

**Comment by Chicken-Go-Crazy** [comment]
lol

**Comment by Chicken-Go-Crazy** [comment]
ima report him he needs to do this himself without our help he stole our code

**Comment by mll-enh** [comment]
why we don't own fnf LMAO

**Comment by Chicken-Go-Crazy** [comment]
idk
